# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fc5009c28fc47fc42243f2d12e5f7a28a5b8ac11906b14df1c0cd4b6550a6e001b74016c7d1a67200be5b87d1fdf96e30fc9017368200b64ded606d8c6946d7d

test:
  secret_key_base: f6a6399121963061a9160c584fd49b8a7aed8743e91f339b7760caf713033ab2d1d139a92afe7f11d1e80b36647270b3928d7ccfb7e2aa03c9c46a9ac386f047

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
